export type detailType = {
  id: string;
  name: string;
  intelligence: string;
  strength: string;
  speed: string;
  durability: string;
  power: string;
  fullName: string;
  birthPlace: string;
  firstAppearance: string;
  gender: string;
  race: string;
  height: string;
  weight: string;
  eyeColor: string;
  hairColor: string;
  occupation: string;
  publisher: string;
  image: string;
};
